### ISSUE TITLE
Incorrect PHPDoc for pub/sub

### ISSUE THREAD

**Issue by JoelFeiner** [clue/reactphp-redis#106]
https://github.com/clue/reactphp-redis/blob/a3630f14cc0852d9b0d4bf8f5732479389215792/src/Client.php#L14

This should be `publish` not `message`. per: https://redis.io/topics/pubsub.

Code works fine, but PHPStan is telling me that the `publish` method doesn't exist. I can workaround with an error override, but it'd be nice to have it fixed.

**Comment by clue** [comment]
@JoelFeiner Thanks for reporting, I can see where you're coming from!

The above documentation uses a non-standard `@event` notation. This is supposed to inform you of the events that are emitted, not the methods that can be called on the interface. You can find the full documentation in the README section: https://github.com/clue/reactphp-redis#pubsub. This is also includes the following example which better highlights this:

```php
$channel = 'user';
$client->subscribe($channel);

$client->on('message', function ($channel, $payload) {
    // pubsub message received on given $channel
    var_dump($channel, json_decode($payload));
});
```

As such, I do not consider this to be "incorrect" but perhaps "not ideal".

Additionally, the `subscribe()` method is exposed through the PHP's magic `__call()` method, which is why static analysis tools may not know about this method. I understand that this may be confusing and/or not obvious, but this is also covered in the existing documentation.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1: In particular, I'm happy to accept PRs if you feel this can be improved somehow! :shipit:

**Comment by JoelFeiner** [comment]
@clue Thanks, that makes sense.

Should there not be PHPDoc for the magic methods? Static tools can handle that, they just need the documentation: https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/method.html. I think that would fix my issue.

**Comment by clue** [comment]
@JoelFeiner I'm not opposed to taking a look at a PR and seeing if it makes sense to merge here :+1: 

That being said, I'm curious how much work this is going to involve in the long run. New Redis versions keep adding new commands and arguments and I'd rather keep the amount of work required to support new Redis versions as small as possible.

**Comment by JoelFeiner** [comment]
@clue I understand that concern. I took a look at the source code for Redis and it looks like their help documentation is stored as a giant C array, fairly well formatted (https://github.com/redis/redis/blob/unstable/src/help.h). If you aren't interested in manually updating the PHP docs, perhaps I could write and contribute a script that would parse the help file and generate the PHP docs automatically. Obviously, that'd be a weekend project some time, if you're at all in favor of such a thing.

**Comment by clue** [comment]
Go for it! :shipit: :shipit: :shipit: 

You can always post the gist here before spending too much time on the automatic conversion, I'm curious what you're coming up with :+1:
