### ISSUE TITLE
Examples needed: pipeline()

### ISSUE THREAD

**Issue by Saso** [clue/reactphp-redis#108]
this is actually not an issue, but more of a question, which I can't get answered online.
I have whole bunch of requests, which I would love to put into pipeline.
As each client implements pipeline their own way, I just don't know, how to do it for my code.
Would you mind giving me an example, please?

take care and keep up the good work :)
 Saso

**Comment by clue** [comment]
@Saso Thanks for bringing this up, excellent question!

Unlike other Redis client implementations, this project will automatically execute all commands in a pipeline and doesn't need any explicit method for this.

```php
$client->get('foo')->then($foo);
$client->get('bar')->then($bar);
```

This library will indeed send both commands at once to the Redis server. The Redis server is guaranteed to execute each command in order, so that you can be guaranteed the first command resolves before the second one. The same logic applies to all commands, including ones that are blocking on the server side (for example `BLPOP`).

**Comment by clue** [comment]
Note that this library is entirely async. This means that in your example, you're adding 40000 commands to the outgoing send queue and creating 40000 promises to represent each command.

A moment later, it will start sending this outgoing send queue and remove this data from PHP memory. Sending a few hundred kilobytes should be completed after a few milliseconds max, but this entirely depends on your architecture (local Redis server, network buffers etc.). Once the first response messages come in after a few milliseconds max, it will resolve the pending promises and again remove them from memory, so PHP's garbage collector can free this memory.

Depending on your use case, you may want to combine multiple keys into a single command, chunk your requests and/or use a streaming approach to not have too many operations pending at once.

For instance, the [`SADD` command](https://redis.io/commands/sadd) supports a variable number of members to add to the same set at once.

You may also want to take a look at https://github.com/clue/reactphp-mq or https://github.com/clue/reactphp-flux to avoid sending too many concurrent requests.

**Comment by Saso** [comment]
hi Clue,
this is exactly, what I did and I used Lua on Redis for help.
Thank you for your answer.

take care, Saso
