### ISSUE TITLE
Using array as parameter in some functions throws fatal error which hangs indefinitely

### ISSUE THREAD

**Issue by maxgalbu** [clue/reactphp-redis#155]
The code:

```php
$vendorIds = [1,2,3];
$db = 18;

$redis = new RedisClient("redis:6379");
return $redis->select($db)
    ->then(function() use ($redis, $vendorIds) {
        return $redis->mget($vendorIds);
    });
```

If I call this in an API, the phpfpm worker and request hangs indefinitely. 
Debugging shows a fatal error [here](https://github.com/clue/php-redis-protocol/blob/271b8009887209d930f613ad3b9518f94bd6b51c/src/Clue/Redis/Protocol/Serializer/RecursiveSerializer.php#L23) - the problem is that `$db` is an int and `strlen` doesn't work on it. Same thing with `$redis->mget($vendorIds);`, argument is an array and strlen is not fit for it. This is related probably: https://github.com/clue/reactphp-redis/issues/17

But one of the issues here is the fatal error that hangs indefinitely, which was weird to find... is this supposed to happen?

PHP 8.1.27
reactphp-promise 3.1.0
reactphp-redis 3.x-dev

**Comment by clue** [comment]
The `MGET` command accepts a variable number of string arguments instead of an array of strings. In your case, this would be as simple as using the splat operator like the latter example:

```php
$redis->mget($vendor1, $vendor2, $vendor3);
$redis->mget(...[$vendor1, $vendor2, $vendor3]);
```

I don't see how the `SELECT` command could cause any problems here (https://3v4l.org/7TFG4), so I don't think this is related to the problem you're seeing.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️
