### ISSUE TITLE
How to call JSON.SET/GET command

### ISSUE THREAD

**Issue by patriksima** [clue/reactphp-redis#94]
Hello,

I'm using Redis JSON module. Is it possible to call it somehow?

**Comment by clue** [comment]
@patriksima Thank you for this excellent question!

This project maps all commands to method calls as is. For [RedisJSON](https://github.com/RedisJSON/RedisJSON) this doesn't work out of the box because it uses commands that are not valid method names in PHP (e.g. `JSON.GET object`). As an alternative, you can always manually call the magic `__call()` method like this:

```php
$client->__call('JSON.GET', ['object']);
```

I hope this helps! :+1:
